databases:
  - name: fomare_DB
    databaseName: fomare_db
    user: fomare
    region: singapore

services:
  - type: web
    name: fomare
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fomare_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

